version: '3'

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: 'TRUE'
      USE_AIKAR_FLAGS: 'TRUE'
      TYPE: PURPUR
      MEMORY: 4G
      VERSION: LATEST
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./src:/data
